# Fichier de configuration pour Netlify
[build]
  command = "npx netlify db init && npm run build"
  publish = ".next"
  
  # IMPORTANT: Définir explicitement le publish directory
  # pour override les paramètres de l'interface
  publish = ".next"

# Plugin officiel pour gérer les spécificités de Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
