# Fichier de configuration pour Netlify
[build]
  # Commande pour construire le site
  command = "next build"
  
  # IMPORTANT: Définir explicitement le publish directory
  # pour override les paramètres de l'interface
  publish = ".next"

# Plugin officiel pour gérer les spécificités de Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
