# Fichier de configuration pour Netlify
[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = ".next"
  
  # IMPORTANT: Définir explicitement le publish directory
  # pour override les paramètres de l'interface

# Plugin officiel pour gérer les spécificités de Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
